### ISSUE TITLE
Integrating with PBS as well as slurm? 

### ISSUE THREAD

**Issue by halexand** [AlexanderLabWHOI/eukrhythmic#36]
Many clusters still run on PBS. How can we make running PBS as straight forward as slurm? 

An initial test for pbs in the submit script here: 

```
snakemake
        --rerun-incomplete --jobs 50 --use-conda --cluster-config cluster-pbs.yaml --cluster "qsub -N {rule}.{wildcards} -l vmem={cluster.mem}gb,walltime={cluster.time},nodes={cluster.nodes}:ppn={cluster.cpupertask}"
```

Can we modify this in the cluster: 

```
  command_options:
    slurm:
      account: --account={}
      command: sbatch --parsable --qos=unlim
      key_mapping: null
      mem: --mem={}gb
      name: --job-name={}
      nodes: -N {}
      queue: --partition={}
      threads: -n {}
      time: --time={}
    pbs:
      command: qsub
      key_mapping: null
      mem: -l vmem={}gb
      name: -N {}
      nodes: -l nodes={}
      queue: –partition={}
      threads: -l ppn={}
      time: -l walltime={}
```

Currently pbs ppn doesn't look quite right.
